### ISSUE TITLE
Include dependent plugins

### ISSUE THREAD

**Issue by suguruTakahashi-1234** [daikimat/depermaid#22]
### Description

Currently, the product specified in `plugins:` in Package.swift is not included in the generated Mermaid when the following command is executed.

```
swift package plugin depermaid --product
```

Please include the product specified in `plugins:` by default in the generated Mermaid, or include it by specifying an option like `--plugin` when executing the command.

**Comment by daikimat** [comment]
@suguruTakahashi-1234 Thanks for bringing this to our attention.

We'll evaluate the possibility of displaying the plugin when using command options like --product or --plugin.

Stay tuned for further updates.

If you have any other questions or suggestions, feel free to reach out.

**Comment by daikimat** [comment]
@suguruTakahashi-1234 
I dug into the [PluginContext](https://github.com/apple/swift-package-manager/blob/f529daef40418e143ed501ff245109e061db190a/Sources/PackagePlugin/Context.swift#L18) that's fetching dependencies, but it seems there's no way to fetch plugins. Looks like we're stuck until SwiftPM gets an update.

Thanks for looking into it.

If you have any more questions or thoughts, feel free to share them here.

Cheers
